# Generated by Django 3.2.15 on 2022-08-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='model_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='password',
            field=models.CharField(default='*', max_length=70),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.CharField(default='', max_length=1500),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(default='No Title', max_length=30),
        ),
    ]
