# Generated by Django 3.2.15 on 2022-08-28 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220828_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='model_num',
            new_name='note_num',
        ),
    ]
