# Generated by Django 3.2.15 on 1980-01-04 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_model_num_note_note_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited', models.IntegerField(default=0)),
                ('str_key', models.CharField(default='9TrSGzqUW4SDUgq', max_length=15)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.note')),
            ],
        ),
    ]
