# Generated by Django 3.2.15 on 1980-01-04 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_tempkey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tempkey',
            old_name='visited',
            new_name='used',
        ),
        migrations.AlterField(
            model_name='tempkey',
            name='str_key',
            field=models.CharField(default='IKXqFAEZlY9XA74', max_length=15),
        ),
    ]
