# Generated by Django 3.2.15 on 1980-01-04 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_19800104_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempkey',
            name='str_key',
            field=models.CharField(default='ECzW91GVhH2LCX5', max_length=15),
        ),
    ]
