# Generated by Django 3.2.15 on 1980-01-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_tempkey_str_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='password',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='tempkey',
            name='str_key',
            field=models.CharField(default='jSTa3Xf7zY0QSK3', max_length=15),
        ),
    ]
