# Generated by Django 3.2.15 on 1980-01-04 00:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_19800104_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tempkey',
            name='str_key',
            field=models.CharField(default='SOawzyl8qY0qCAx', max_length=15),
        ),
    ]
